version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /tmp/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    command: "-notify-sighup nginx -watch -only-exposed -wait 5s:30 /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    volumes:
      - /tmp/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports: ~
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    environment:
      - VIRTUAL_HOST=whoami.local
    image: jwilder/whoami
