version: '2'
# make sure you search for and replace the below settings
  # /path/to/certs - search for the path to the certifications and replace with the correct path
  # /path/to/nginx.tmpl - search for the path to nginx.tmpl and replace with the correct path

services:

  #Nginx server

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      volumes:
        - /etc/nginx/conf.d
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
        - /path/to/certs:/etc/nginx/certs:ro

  #nginx-gen
  #repository   https://github.com/jwilder/docker-gen
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes_from: nginx
    volumes:
      - /path/to/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx -watch -only-exposed -wait 5s:30 /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
